// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) 
	{
	    int N = Integer.parseInt(args[0]);
		int numUnder = 0, numOver = 0;
		double sumUnder = 0, sumOver = 0;
		double numRandom, ratio = 0;
		if (N<=0)
		   System.out.println("N must be non-negative");
		else
		{
			for (int i=0; i<N; i++)
			{
				numRandom = Math.random();
				if (numRandom <= 0.5)
				{
					numUnder++;
					sumUnder += numRandom;
				}
				else
				{
					numOver++;
					sumOver += numRandom;
				}
			}
			if (sumOver > sumUnder && sumOver != 0)
			   ratio = sumUnder / sumOver;
			if (sumOver <= sumUnder && sumUnder != 0)
			   ratio = sumOver / sumUnder;
			System.out.println("> 0.5: " + numOver + " times");
			System.out.println("<= 0.5: " + numUnder + " times");
			if (ratio != 0)
			   System.out.println("Ratio: " + ratio);
		}
	}
}
